services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:16.6
    ports:
      - "5432:5432"
    env_file: .env.db
